services:
  db:
    image: mariadb:11
    container_name: mariadb-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: usf6FFdMfLXgAGqORnmR8
      MYSQL_DATABASE: bhhcfb8lkdjzm7yexzpq
      MYSQL_USER: ukiui5tx8fkytjk
      MYSQL_PASSWORD: usf6FFdMfLXgAGqORnmR8
    ports:
      - "3306:3306"
    volumes:
      - mariadbdata:/var/lib/mysql      
      - ./Backend/db.sql:/docker-entrypoint-initdb.d/db.sql

  backend:
    build: ./Backend
    container_name: node-backend
    restart: always
    ports:
      - "3015:3015"
    depends_on:
      - db
    environment:
      PORT: 3015
      DB_HOST: db
      DB_USER: ukiui5tx8fkytjk
      DB_PASSWORD: usf6FFdMfLXgAGqORnmR8
      DB_NAME: bhhcfb8lkdjzm7yexzpq
      DB_PORT: 3306
      JWT_SECRET: ecommerce_artisan_platform_secret_key
    volumes:
      - ./Backend:/usr/src/app
      - ./Media:/usr/src/app/Media
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: npm run dev

  frontend:
    build: ./Frontend
    container_name: node-frontend
    restart: always
    ports:
      - "3010:80"
    depends_on:
      - backend
    volumes:
      - ./Frontend:/usr/share/nginx/html
      - ./Media:/usr/share/nginx/html/Media

volumes:
  mariadbdata: 