services:
  # Production database - persistent data
  db:
    image: mariadb:11
    container_name: ecommerce-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
      MYSQL_INNODB_BUFFER_POOL_SIZE: 256M
      MYSQL_INNODB_LOG_FILE_SIZE: 128M
      MYSQL_INNODB_FLUSH_LOG_AT_TRX_COMMIT: 1
      MYSQL_INNODB_FLUSH_METHOD: O_DIRECT
      MYSQL_ROOT_HOST: '%'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /mnt/condivisa/panesalame_data/database:/var/lib/mysql
      - "/mnt/condivisa/Scuola/Universita/Terzo Anno/Tecnologie Innovative per lo sviluppo Web/ecommerce/Backend/db.sql:/docker-entrypoint-initdb.d/db.sql:ro"
    networks: 
      - ecommerce-internal

  # Production backend API
  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    image: panesalame/backend:latest
    container_name: ecommerce-backend
    depends_on:
      - db
    environment:
      NODE_ENV: development
      PORT: 3015
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: 1234
      DB_NAME: ecommerce_db
      DB_PORT: 3306
      JWT_SECRET: ecommerce_secret_key_2024
    volumes:
      - "/mnt/condivisa/Scuola/Universita/Terzo Anno/Tecnologie Innovative per lo sviluppo Web/ecommerce/Backend:/usr/src/app/src:ro"
      - /mnt/condivisa/panesalame_data/media:/data/media
      - backend-node-modules:/usr/src/app/node_modules
    networks:  # AGGIUNTO: Permette al frontend di parlare col backend
      - ecommerce-internal

  # Image server
  imageserver:
    image: nginx:alpine
    container_name: ecommerce-imageserver
    restart: always
    volumes:
      - /mnt/condivisa/panesalame_data/media:/usr/share/nginx/html/Media:ro
    depends_on:
      - backend
    networks: # AGGIUNTO: Permette la comunicazione interna
      - ecommerce-internal

  # Production frontend server
  frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    image: panesalame/frontend:latest
    container_name: ecommerce-frontend
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: https://api.panesalame.andrea-mauri.duckdns.org
    networks:
      - ecommerce-internal # Comunica con il backend
      - web-proxy 

  # Monitoring system
  monitoring:
    build:
      context: .
      dockerfile: Monitoring/Dockerfile
    image: panesalame/monitoring:latest
    container_name: ecommerce-monitoring
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/condivisa/panesalame_data/media:/data/Media
      - "/mnt/condivisa/Scuola/Universita/Terzo Anno/Tecnologie Innovative per lo sviluppo Web/ecommerce/Test/Output:/data/Test/Output"
      - "/mnt/condivisa/Scuola/Universita/Terzo Anno/Tecnologie Innovative per lo sviluppo Web/ecommerce/backups:/usr/src/app/backups"
      - "/mnt/condivisa/Scuola/Universita/Terzo Anno/Tecnologie Innovative per lo sviluppo Web/ecommerce/README.md:/usr/src/app/README.md:ro"
      - "/mnt/condivisa/Scuola/Universita/Terzo Anno/Tecnologie Innovative per lo sviluppo Web/ecommerce/docker-compose-testing.yml:/usr/src/app/docker-compose-testing.yml:ro"
      - "/mnt/condivisa/Scuola/Universita/Terzo Anno/Tecnologie Innovative per lo sviluppo Web/ecommerce/Documenti:/usr/src/app/Documenti:ro"
      - "/mnt/condivisa/Scuola/Universita/Terzo Anno/Tecnologie Innovative per lo sviluppo Web/ecommerce/safe-versions:/usr/src/app/safe-versions:ro" # <-- RIGA AGGIUNTA
    environment:
      NODE_ENV: production
      PORT: 3017
    depends_on:
      - backend
      - frontend
    networks:
      - ecommerce-internal # Comunica con gli altri container dello stack
      - web-proxy          # Comunica con il mondo esterno tramite NPM
volumes:
  backend-node-modules:

networks:
  web-proxy:
    external: true # La rete per parlare con il mondo, gestita esternamente
  ecommerce-internal: {}
    # Una rete interna solo per questo stack, per far parlare i container tra loro in sicurezza