services:
  db:
    image: mariadb:11
    container_name: mariadb-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: usf6FFdMfLXgAGqORnmR8
      MYSQL_DATABASE: bhhcfb8lkdjzm7yexzpq
      MYSQL_USER: ukiui5tx8fkytjk
      MYSQL_PASSWORD: usf6FFdMfLXgAGqORnmR8
    ports:
      - "3306:3306"
    volumes:
      - mariadbdata:/var/lib/mysql      
      - ./Backend/db.sql:/docker-entrypoint-initdb.d/db.sql

  # Database di test
  db-test:
    image: mariadb:11
    container_name: mariadb-test-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test_password
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    ports:
      - "3307:3306"
    volumes:
      - mariadbtest:/var/lib/mysql
      - ./Backend/db.sql:/docker-entrypoint-initdb.d/db.sql

  backend:
    build: ./Backend
    container_name: node-backend
    restart: always
    ports:
      - "3015:3015"
    depends_on:
      - db
    environment:
      PORT: 3015
      DB_HOST: db
      DB_USER: ukiui5tx8fkytjk
      DB_PASSWORD: usf6FFdMfLXgAGqORnmR8
      DB_NAME: bhhcfb8lkdjzm7yexzpq
      DB_PORT: 3306
      JWT_SECRET: ecommerce_artisan_platform_secret_key
    volumes:
      - ./Backend:/usr/src/app
      # Volume condiviso per le immagini caricate dagli utenti
      - ./Media:/usr/src/app/Media
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: npm run dev

  # Servizio di test integrativi
  test-integrativi:
    build: 
      context: .
      dockerfile: ./Test/Backend-Integrativi/Dockerfile
    ports:
      - "3016:3016"
    depends_on:
      - db-test
    environment:
      PORT: 3016
      DB_HOST: db-test
      DB_USER: test_user
      DB_PASSWORD: test_password
      DB_NAME: test_db
      DB_PORT: 3306
      JWT_SECRET: test_secret_key
      NODE_ENV: test
    volumes:
      # - ./Backend:/usr/src/app/Backend  # RIMOSSO per evitare problemi con node_modules
      - ./Test/Backend-Integrativi:/usr/src/app/Test/Backend-Integrativi
      - ./Media-Test:/usr/src/app/Media-Test

  # Servizio di test unitari del backend
  test-unitari:
    build:
      context: .
      dockerfile: ./Test/Backend-Unitari/Dockerfile
    depends_on:
      - backend
    environment:
      NODE_ENV: test
    volumes:
      - ./Backend:/usr/src/app/Backend
      - ./Test/Backend-Unitari:/usr/src/app/Test/Backend-Unitari

  # Servizio di test del frontend
  test-frontend:
    build:
      context: .
      dockerfile: ./Test/Frontend/Dockerfile
    depends_on:
      - frontend
    environment:
      NODE_ENV: test
    volumes:
      - ./Frontend:/usr/src/app/Frontend
      - ./Test/Frontend:/usr/src/app/Test/Frontend

  frontend:
    build: ./Frontend
    container_name: node-frontend
    restart: always
    ports:
      - "3010:80"
    depends_on:
      - backend
    volumes:
      - ./Frontend:/usr/share/nginx/html
      # NON montare ./Media qui, le immagini pubbliche sono servite da imageserver

  imageserver:
    image: nginx:alpine
    container_name: imageserver
    restart: always
    ports:
      - "8080:80"
    volumes:
      # Volume condiviso per le immagini pubbliche
      - ./Media:/usr/share/nginx/html/Media
      
volumes:
  mariadbdata:
  mariadbtest: