services:
  # Production database - persistent data
  db:
    image: mariadb:11
    container_name: ecommerce-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /mnt/condivisa/Scuola/Universita/Terzo Anno/Tecnologie Innovative per lo sviluppo Web/ecommerce/panesalame_data/database:/var/lib/mysql
      - "/mnt/condivisa/Scuola/Universita/Terzo Anno/Tecnologie Innovative per lo sviluppo Web/ecommerce/Backend/db.sql:/docker-entrypoint-initdb.d/db.sql:ro"
    networks:
      - ecommerce-internal
    healthcheck: # <--- AGGIUNTO: CONTROLLA SE IL DB È PRONTO
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10

  # Production backend API
  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    image: panesalame/backend:latest
    container_name: ecommerce-backend
    restart: unless-stopped
    depends_on: # <--- MODIFICATO: ATTENDE CHE IL DB SIA "HEALTHY"
      db:
        condition: service_healthy
    environment:
      NODE_ENV: development
      PORT: 3015
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: 1234
      DB_NAME: ecommerce_db
      DB_PORT: 3306
      JWT_SECRET: ecommerce_secret_key_2024
    volumes:
      - /mnt/condivisa/Scuola/Universita/Terzo Anno/Tecnologie Innovative per lo sviluppo Web/ecommerce/panesalame_data/media:/usr/src/app/Media
    networks:
      - ecommerce-internal
      - web-proxy

  # Image server
  imageserver:
    image: nginx:alpine
    container_name: ecommerce-imageserver
    restart: unless-stopped
    volumes:
      - /mnt/condivisa/Scuola/Universita/Terzo Anno/Tecnologie Innovative per lo sviluppo Web/ecommerce/panesalame_data/media:/usr/share/nginx/html/Media:ro
    depends_on:
      - backend
    networks:
      - ecommerce-internal
      - web-proxy

  # Production frontend server
  frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    image: panesalame/frontend:latest
    container_name: ecommerce-frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: https://api.panesalame.andrea-mauri.duckdns.org
    networks:
      - ecommerce-internal
      - web-proxy

  # Monitoring system
  monitoring:
    build:
      context: .
      dockerfile: Monitoring/Dockerfile
    image: panesalame/monitoring:latest
    container_name: ecommerce-monitoring
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/condivisa/panesalame_data/media:/data/Media
      - "/mnt/condivisa/Scuola/Universita/Terzo Anno/Tecnologie Innovative per lo sviluppo Web/ecommerce/Test/Output:/data/Test/Output"
      - "/mnt/condivisa/Scuola/Universita/Terzo Anno/Tecnologie Innovative per lo sviluppo Web/ecommerce/backups:/usr/src/app/backups"
      - "/mnt/condivisa/Scuola/Universita/Terzo Anno/Tecnologie Innovative per lo sviluppo Web/ecommerce/README.md:/usr/src/app/README.md:ro"
      - "/mnt/condivisa/Scuola/Universita/Terzo Anno/Tecnologie Innovative per lo sviluppo Web/ecommerce/docker-compose-testing.yml:/usr/src/app/docker-compose-testing.yml:ro"
      - "/mnt/condivisa/Scuola/Universita/Terzo Anno/Tecnologie Innovative per lo sviluppo Web/ecommerce/Documenti:/usr/src/app/Documenti:ro"
      - "/mnt/condivisa/Scuola/Universita/Terzo Anno/Tecnologie Innovative per lo sviluppo Web/ecommerce/safe-versions:/usr/src/app/safe-versions:ro"
    environment:
      NODE_ENV: production
      PORT: 3017
    depends_on:
      - backend
      - frontend
    networks:
      - ecommerce-internal
      - web-proxy

volumes:
  backend-node-modules:

networks:
  web-proxy:
    external: true
  ecommerce-internal: {}