services:
  # Test database - ottimizzato per esecuzione veloce dei test
  db-test:
    image: mariadb:11
    container_name: mariadb-test-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ecommerce_test_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
      # Ottimizzazione per test - disabilita durability per velocità
      MYSQL_INNODB_FLUSH_LOG_AT_TRX_COMMIT: 0
      MYSQL_INNODB_FLUSH_METHOD: O_DIRECT
      MYSQL_INNODB_BUFFER_POOL_SIZE: 128M
      # Configurazioni aggiuntive per test
      MYSQL_QUERY_CACHE_SIZE: 32M
      MYSQL_SYNC_BINLOG: 0
    ports:
      - "3016:3306"
    volumes:
      - test_db_data:/var/lib/mysql
      - ./Backend/db.sql:/docker-entrypoint-initdb.d/db.sql
    # Utilizzo tmpfs per i log per ridurre I/O
    tmpfs:
      - /tmp
      - /var/log
    # Health check ottimizzato per test
    healthcheck:
      test: ["CMD", "mariadb", "-h", "localhost", "-u", "admin", "-p1234", "-e", "SELECT 1;"]
      start_period: 20s
      interval: 5s
      timeout: 3s
      retries: 6
      start_interval: 2s

  # Backend per test - utilizza database di test
  backend-test:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: test
      DB_HOST: mariadb-test-db
      DB_PORT: 3016
      DB_USER: ecommerce
      DB_PASSWORD: ecommerce
      DB_NAME: ecommerce_test
      JWT_SECRET: test_secret
      PORT: 3010
    ports:
      - "3017:3010"
    depends_on:
      - mariadb-test-db
    networks:
      - ecommerce_default
    volumes:
      - ./Backend:/usr/src/app
      - test-reports:/usr/src/app/Test/Output

  # Test unitari backend - isolati, senza dipendenze esterne
  test-unitari:
    build:
      context: ./Test/Backend-Unitari
      dockerfile: Dockerfile
    environment:
      NODE_ENV: test
      DB_HOST: mariadb-test-db
      DB_PORT: 3016
      DB_USER: ecommerce
      DB_PASSWORD: ecommerce
      DB_NAME: ecommerce_test
    depends_on:
      - mariadb-test-db
      - backend-test
    networks:
      - ecommerce_default
    volumes:
      - ./Test/Output:/usr/src/app/Test/Output
    working_dir: /usr/src/app/Test/Backend-Unitari
    restart: "no"

  # Test integrativi backend - richiede database di test e backend
  test-integrativi:
    build:
      context: ./Test/Backend-Integrativi
      dockerfile: Dockerfile
    environment:
      NODE_ENV: test
      DB_HOST: mariadb-test-db
      DB_PORT: 3016
      DB_USER: ecommerce
      DB_PASSWORD: ecommerce
      DB_NAME: ecommerce_test
    depends_on:
      - mariadb-test-db
      - backend-test
    networks:
      - ecommerce_default
    volumes:
      - ./Test/Output:/usr/src/app/Test/Output
    working_dir: /usr/src/app/Test/Backend-Integrativi
    restart: "no"

  # Test frontend - testing DOM con jsdom
  test-frontend:
    build:
      context: ./Test/Frontend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: test
      REACT_APP_API_URL: http://backend-test:3015
    volumes:
      - ./Test/Output:/usr/src/app/Test/Output
    working_dir: /usr/src/app/Test/Frontend
    restart: "no"

  # Test performance - load testing e benchmark
  test-performance:
    build:
      context: ./Test/Performance
      dockerfile: Dockerfile
    environment:
      NODE_ENV: test
      API_BASE_URL: http://backend-test:3015
    volumes:
      - ./Test/Output:/usr/src/app/Test/Output
    working_dir: /usr/src/app/Test/Performance
    restart: "no"

  # Monitoring system per environment di test
  monitoring-test:
    build: ./Monitoring
    container_name: ecommerce-monitoring-test
    ports:
      - "3018:3017"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./Media:/usr/src/app/Media:ro
      - ./Backend:/usr/src/app/Backend:ro
      - ./Frontend:/usr/src/app/Frontend:ro
      - ./Test:/usr/src/app/Test:ro
      - ./Monitoring:/usr/src/app/Monitoring:ro
      - ./Monitoring/public:/usr/src/app/public
    environment:
      NODE_ENV: test
    ports:
      - "3013:3012"
    depends_on:
      - backend-test
    restart: "no"

volumes:
  test_db_data:   # Persistenza dati test (limitata alla sessione)